spring.application.name=servidor

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# Configuracion de Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379
